.\"                              hey, Emacs:   -*- nroff -*-
.\" macchanger is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH MACCHANGER 1 "September 21, 2026"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
macchanger \- MAC Changer
.SH SYNOPSIS
.B macchanger
.RI [ options ]
.RI device
.SH DESCRIPTION
\fBmacchanger\fP is a GNU/Linux utility for viewing/manipulating the MAC address for network interfaces.
.\" .PP
.\" It also...
.SH OPTIONS
\fBmacchanger\fP accepts the following options:
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Show version of program.
.TP
.B \-s, \-\-show
Prints the current MAC. This is the default action when no other option is specified.
.TP
.B \-e, \-\-ending
Don't change the vendor bytes.
.TP
.B \-a, \-\-another
Set a random vendor MAC of the same kind. A wireless interface, detected
from sysfs, gets another wireless vendor. Any other interface gets a
non-wireless vendor.
.TP
.B \-A
Set random vendor MAC of any kind.
.TP
.B \-r, \-\-random
Set fully random MAC.
.TP
.B \-p, \-\-permanent
Reset MAC address to its original, permanent hardware value.
.TP
.B \-l, \-\-list[=keyword]
Print known vendors. The keyword matches a whole word in the vendor
description, ignoring case, so
.I Intel
does not match
.IR Intelligent .
It may be written as
.BR \-\-list=keyword ,
.BR \-\-list\ keyword ,
or
.BR \-l keyword .
.TP
.B \-b, \-\-bia
When setting a fully random MAC, pretend to be a burned-in address. Without
this option the MAC has the locally administered bit set.
.TP
.B \-m, \-\-mac XX:XX:XX:XX:XX:XX, \-\-mac=XX:XX:XX:XX:XX:XX
Set the MAC XX:XX:XX:XX:XX:XX. Dashes may be used instead of colons, and a
12-digit hexadecimal string is also accepted. Asking for the address the
interface already has succeeds without changing it. Multicast addresses are refused.
.SH NOTES
Some drivers accept a new address only while the interface is down. When
the kernel reports that the device is busy,
.B macchanger
brings the interface down, applies the address, and restores its previous
administrative state. It then reads the address back. If the driver
ignored the request, the command prints an error and exits non-zero.
.PP
A program that manages the interface, commonly NetworkManager, may restore
the permanent address when the interface comes back up. To keep a chosen
address, set the connection's cloned MAC address or do not let that program
manage the device.
.PP
.B \-\-random
produces a unicast address with the locally administered bit set.
.B \-\-bia
clears that bit. Neither form is drawn from the vendor list;
.B \-a
and
.B \-A
are.
.SH EXAMPLE
macchanger \-A eth1
.SH "SEE ALSO"
ip (8),
ip-link (8),
ethtool (8)
.\" .BR foo (1),
.SH AUTHOR
Alvaro Lopez Ortega <alvaro@alobbs.com>.
Updates: byte@jvmlab.org.
